import { useEffect } from 'react'

const POLL_INTERVAL_MS = 3_000

/**
 * While tickets are still being generated by the async worker,
 * refetch periodically until they become valid.
 * `data` is the latest response; each new response schedules the next poll.
 * (With the real backend this could become a WebSocket/SSE subscription.)
 */
export function useProcessingPoll(isProcessing: boolean, reload: () => void, data: unknown) {
  useEffect(() => {
    if (!isProcessing) return
    const timer = window.setTimeout(reload, POLL_INTERVAL_MS)
    return () => window.clearTimeout(timer)
  }, [isProcessing, reload, data])
}
